# Generated by Django 5.0.6 on 2024-05-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_alter_actor_main_picture_alter_director_main_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='filmy.movie'),
        ),
    ]
