# Generated by Django 5.0.6 on 2024-05-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0008_actor_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='filmy.movie'),
        ),
    ]
