# Generated by Django 5.0.6 on 2024-06-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_alter_actor_main_picture_alter_director_main_picture_and_more'),
        ('filmy', '0005_movie_actors_movie_director_movie_genres'),
        ('filmy', '0010_remove_actor_movies_remove_genre_movies'),
    ]

    operations = [
    ]
